// tool/verify_docs.dart
//
// Lightweight script to detect stale assertions in docs/*.md
// before trusting those docs for code generation.
//
// Usage: dart run tool/verify_docs.dart
//
// Checks:
//   1. @source file paths in docs exist in the repo
//   2. Legacy backup keys referenced in docs/storage-contract.md match legacy_backup_box_names.dart
//   3. Key service classes referenced in docs exist in service package roots
//
// This is not a CI gate. It is a quick sanity check.
// Exit code 0 = all checks pass. Non-zero = issue found.

import 'dart:io';

final _repoRoot = Directory.current.path;
final _docsDir = Directory('$_repoRoot/docs');
final _libDir = '$_repoRoot/lib';
final _legacyBackupBoxNamesFile = File(
  '$_libDir/storage/legacy_backup_box_names.dart',
);
final _serviceDirs = [
  Directory('$_libDir/services'),
  Directory('$_repoRoot/packages/flow_ai/lib/src'),
  Directory('$_repoRoot/packages/flow_dictionary/lib/src'),
  Directory('$_repoRoot/packages/flow_language/lib'),
];

void main(List<String> args) {
  var allOk = true;

  if (!_docsDir.existsSync()) {
    stderr.writeln('[FAIL] docs/ directory not found');
    exit(1);
  }

  final docFiles = _docsDir
      .listSync()
      .whereType<File>()
      .where((f) => f.path.endsWith('.md'))
      .toList();

  if (docFiles.isEmpty) {
    stderr.writeln('[WARN] No .md files in docs/');
    exit(0);
  }

  stdout.writeln('=== Flow Read Doc Freshness Check ===');
  stdout.writeln('Checking ${docFiles.length} doc(s)...\n');

  // ── Check 1: @source paths ────────────────────────────────
  stdout.writeln('── @source path check ──');
  for (final doc in docFiles) {
    final lines = doc.readAsLinesSync();
    for (var i = 0; i < lines.length; i++) {
      final line = lines[i];
      final match = RegExp(r'@source\s+(.+)').firstMatch(line);
      if (match != null) {
        final paths = match.group(1)!.split(RegExp(r'\s+'));
        for (final relPath in paths) {
          final trimmed = relPath.trim();
          if (trimmed.isEmpty) continue;
          final fullPath = '$_repoRoot/$trimmed';
          if (!File(fullPath).existsSync() &&
              !Directory(fullPath).existsSync()) {
            stderr.writeln(
              '  [FAIL] ${doc.path.replaceFirst(_repoRoot, '')}:${i + 1} '
              '@source "$trimmed" not found',
            );
            allOk = false;
          }
        }
      }
    }
  }

  if (!allOk) stdout.writeln('  (some @source paths are stale)\n');

  // ── Check 2: Legacy backup keys in docs/storage-contract.md ─
  stdout.writeln('');
  stdout.writeln('── Legacy backup key check ──');
  final storageContractFile = File('${_docsDir.path}/storage-contract.md');
  if (storageContractFile.existsSync()) {
    final docContent = storageContractFile.readAsStringSync();
    final boxNamesCode = _legacyBackupBoxNamesFile.existsSync()
        ? _legacyBackupBoxNamesFile.readAsStringSync()
        : '';

    // Extract concrete backup keys from doc code spans.
    final docBoxNames = <String>{};
    for (final m in RegExp(r'`(\w+)`').allMatches(docContent)) {
      final name = m.group(1)!;
      if (name.endsWith('_{lang}') ||
          name.startsWith('word_') ||
          name == 'settings' ||
          name == 'rss_subscriptions' ||
          name == 'word_levels' ||
          name == 'books_en' ||
          name.endsWith('_en') ||
          name == 'user_vocabulary_en') {
        docBoxNames.add(name);
      }
    }

    // Extract static backup keys from legacy_backup_box_names.dart.
    final codeBoxNames = <String>{};
    for (final m in RegExp(
      r"static const (\w+)\s*=\s*'([^']+)'",
    ).allMatches(boxNamesCode)) {
      final name = m.group(1)!;
      if (name != 'defaultLanguageCode' && name != 'activeSourceLanguageKey') {
        codeBoxNames.add(m.group(2)!);
      }
    }
    // Computed names are dynamic patterns and are intentionally ignored here.

    stdout.writeln(
      '  storage-contract.md: ~${docBoxNames.length} names referenced, '
      'legacy_backup_box_names.dart: ${codeBoxNames.length} static names',
    );

    // Computed keys such as books_en are generated by helper methods.
    final concreteDocNames = docBoxNames
        .where((n) => !n.contains('{lang}'))
        .toSet();
    for (final name in concreteDocNames) {
      if (!codeBoxNames.contains(name)) {
        // Allow known patterns like `books_en`, `user_vocabulary_en` which are generated
        if (!name.endsWith('_en')) {
          stderr.writeln(
            '  [WARN] storage-contract.md references backup key "$name" '
            'not found as static constant in legacy_backup_box_names.dart',
          );
        }
      }
    }
  } else {
    stdout.writeln('  (docs/storage-contract.md not found, skipping)');
  }

  // ── Check 3: Key service classes exist ─────────────────────
  stdout.writeln('');
  stdout.writeln('── Service class existence check ──');
  final keyServices = <String>{
    'DictionaryManagerService',
    'BookService',
    'EpubService',
    'AIService',
    'AICacheService',
    'PromptBuilder',
    'ChapterAIJob',
    'SettingsService',
    'BackupService',
    'ReadingSearchService',
    'UserVocabularyService',
    'WordLevelService',
    'LearningAnalyticsService',
    'CompoundWordAnalyzer',
    'LanguageRegistry',
    'EnglishLanguageModule',
    'ReadingAssistantAgent',
  };

  for (final className in keyServices) {
    final result = _grepAny('class $className', _serviceDirs);
    if (result.isEmpty) {
      stderr.writeln(
        '  [FAIL] Class "$className" not found in service package roots',
      );
      allOk = false;
    }
  }
  stdout.writeln('  All ${keyServices.length} key service classes found.');

  // ── Result ─────────────────────────────────────────────────
  stdout.writeln('');
  if (allOk) {
    stdout.writeln('[PASS] All checks passed, docs are consistent with code.');
    exit(0);
  } else {
    stderr.writeln(
      '[FAIL] Some checks failed. See above for details.\n'
      '  Fix: update the stale doc references, or update code to match docs.',
    );
    exit(1);
  }
}

String _grepAny(String pattern, List<Directory> dirs) {
  for (final dir in dirs) {
    final result = _grep(pattern, dir);
    if (result.isNotEmpty) return result;
  }
  return '';
}

/// Simple recursive grep for a pattern in a directory.
String _grep(String pattern, Directory dir) {
  if (!dir.existsSync()) return '';
  for (final entity in dir.listSync(recursive: true)) {
    if (entity is File && entity.path.endsWith('.dart')) {
      try {
        final content = entity.readAsStringSync();
        if (content.contains(pattern)) {
          return entity.path;
        }
      } catch (_) {
        // skip unreadable files
      }
    }
  }
  return '';
}
